apiVersion: v1
kind: Secret
metadata:
 name: secretsql
 namespace: project
 labels:
  app: sql
type: Opaque
stringData:
 test-database-uri: ${testURI}
 database-uri: ${prodURI}
 secret-key: ${secretkey}