apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: project
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: project
  labels:
    app: front
spec:
  selector:
    app: front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP  

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: project
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---