version: "3.7"

services:
  
  backend:
    build: ./Backend
    image: sherazshahid017/mavenbuild:latest
    container_name: backend
    ports:
    - target: 8081
      published: 8081
      protocol: tcp

  frontend:
    build: ./frontend
    image: sherazshahid017/frontend:latest
    container_name: frontend
    ports:
    - target: 80
      published: 5000
      protocol: tcp
     