- hosts: 
  become: true
  tasks:
  - name: Update VM
    apt:
        update-cache: yes

  - name: Install PyTest
      apt:
        name: python3-pytest
        state: latest

  - name: Install mysql
    apt:
      name: mysql-server
      state: latest

  - name: Copy docker-install.sh
    copy:
      src: docker-install.sh
      dest: /root
      owner: root
 
  - name: Run docker-install.sh
    command: sh /root/docker-install.sh